# Change baseurl before deploy
baseurl = "https://chunyen.xyz/"
languageCode = "zh-tw"
paginate = 10
title = "CY | 程式小角落"
theme = "hugo-theme-stack"


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Static
staticDir = ["static"]

# SEO
enableRobotsTXT = true
googleAnalytics = "G-P1Y8DR82ZX"

[sitemap]
filename = "sitemap-index.xml"

[author]
    email = "admin@chunyen.xyz"
    name = "陳雋諺, Chun-Yen Chen"
