kind: pipeline
type: docker
name: deploy-to-github

steps:
- name: submodule-update
  image: alpine/git
  commands:
    - git submodule update --init --recursive

- name: build
  image: klakegg/hugo
  commands:
    - hugo -D

- name: publish  
  image: plugins/gh-pages
  settings:
    username: 
      from_secret: username
    password: 
      from_secret: password
    pages_directory: public/