kind: pipeline
name: deploy-to-github

steps:
- name: build
  image: AzurCrystal/drone-hugo:update-1.18.3
  settings:
    hugo_version: 0.95
    extended: true
    validate: true
    config: config.yml
    content: content
    validate: true
  commands:
    - apk add libc6-compat libstdc++
    - /bin/drone-hugo

- name: publish  
  image: plugins/gh-pages
  settings:
    username: username
    password: password
    pages_directory: public/