kind: pipeline
name: deploy-to-github

steps:
- name: build
  image: hypervtechnics/drone-hugo
  settings:
    hugo_version: 0.95
    validate: true

- name: publish  
  image: plugins/gh-pages
  settings:
    username: username
    password: password
    pages_directory: public/