kind: pipeline
name: deploy-to-github

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.95
    extended: true
    validate: true
    config: config.yml
    content: content
    validate: true

- name: publish  
  image: plugins/gh-pages
  settings:
    username: username
    password: password
    pages_directory: public/