kind: pipeline
type: docker
name: deploy-to-github

steps:
- name: build
  image: klakegg/hugo
  commands:
    - hugo -t stack

- name: publish  
  image: plugins/gh-pages
  settings:
    username: username
    password: password
    pages_directory: public/